spring:
  profiles:
    active: ES,cat
ank:
  jdbc:
    username: ymlusername
    password: ymlpassword
    url: jdbc.oracle.thin:localhost:1521:orcl
  jdbc1:
    username: ymlusername
    password: ymlpassword
    url: jdbc.oracle.thin:localhost:1521:orcl1
